[build]
  functions = "functions"
  
[[redirects]]
  from = "/pusher/auth"
  to = "/.netlify/functions/auth"
  status = 204
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Headers = "Content-Type, Authorization", Access-Control-Allow-Methods = "POST, OPTIONS"}
  conditions = {Methods = ["OPTIONS"]}